#!/bin/sh
echo "HamoniKR Rescue bootloader setup.">&2
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "HamoniKR install" {
        set isofile="hamonikr.iso"
        loopback loop (hd0,1)/iso/$isofile
        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/iso/hamonikr.iso locale=ko_KR noprompt noeject quiet splash install
        initrd (loop)/casper/initrd.lz
}

menuentry "HamoniKR backup" {
        set isofile="hamonikr.iso"
        loopback loop (hd0,1)/iso/$isofile
        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/iso/hamonikr.iso locale=ko_KR noprompt noeject quiet splash backup
        initrd (loop)/casper/initrd.lz
}

menuentry "HamoniKR restore" {
        set isofile="hamonikr.iso"
        loopback loop (hd0,1)/iso/$isofile
        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/iso/hamonikr.iso locale=ko_KR noprompt noeject quiet splash restore
        initrd (loop)/casper/initrd.lz
}

menuentry "Multicast server" {
        set isofile="hamonikr.iso"
        loopback loop (hd0,1)/iso/$isofile
        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/iso/hamonikr.iso locale=ko_KR noprompt noeject quiet splash server
        initrd (loop)/casper/initrd.lz
}

menuentry "Multicast client" {
        set isofile="hamonikr.iso"
        loopback loop (hd0,1)/iso/$isofile
        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/iso/hamonikr.iso locale=ko_KR noprompt noeject quiet splash client
        initrd (loop)/casper/initrd.lz
}

